from pydantic import BaseModel, Field
from typing import Optional


class Dialogue(BaseModel):
    question: Optional[str] = Field(
        None,
        description="the question to be answered by the LLM",
    )

    context: Optional[str] = Field(
        None,
        description="the contextual knowledge to be used by the LLM",
    )
    
    answer: Optional[str] = Field(
        None,
        description="the answer to the question, as generated by the LLM",
    )

    error: Optional[str] = Field(
        None,
        description="error message",
    )
